[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
call_target = "4rPLqoMbtPAMdYeytQagQyt5ucVxRJpx7BjL2jW49UsQ"
precheck = "kXGFCQ2Bhj5z2zV9pPS7Ygz1PVt3EVYR7zTAGGcx7h9"
rip7755_inbox = "2nfLnXeeWyAUBsCT8uskj8nvkk46FiwaaVvDx29zQcue"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
